name: CI-CD-Pipeline

on:
  push:
    branches: [ main ] # запускать при пуше в любую из этих веток

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Копируем код в облако
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Устанавливаем зависимости (Jest)
        run: npm install

      - name: Запускаем тесты
        run: npm test